"""

Revision ID: 2540e3b1f0bd
Revises: 
Create Date: 2020-09-13 19:08:12.437322

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2540e3b1f0bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('url', sa.Text(), nullable=False),
                    sa.Column('title', sa.Text(), nullable=False),
                    sa.Column('short_description', sa.Text(), nullable=False),
                    sa.Column('datetime', sa.DateTime(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('status', sa.Text(), nullable=False),
                    sa.Column('error', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__article')),
                    sa.UniqueConstraint('url', name=op.f('uq__article__url'))
                    )
    op.create_table('scrap_task',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('handler', sa.Text(), nullable=True),
                    sa.Column('url', sa.Text(), nullable=False),
                    sa.Column('status', sa.Text(), nullable=False),
                    sa.Column('result', sa.JSON(), nullable=True),
                    sa.Column('error', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk__scrap_task'))
                    )
    op.create_table('scrap_document_fields',
                    sa.Column('id', sa.Integer(), autoincrement=True,
                              nullable=False),
                    sa.Column('scrap_task_id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('xpath', sa.Text(), nullable=False),
                    sa.ForeignKeyConstraint(['scrap_task_id'],
                                            ['scrap_task.id'], name=op.f(
                            'fk__scrap_document_fields__scrap_task_id__scrap_task')),
                    sa.PrimaryKeyConstraint('id', name=op.f(
                        'pk__scrap_document_fields'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrap_document_fields')
    op.drop_table('scrap_task')
    op.drop_table('article')
    # ### end Alembic commands ###
